version: '3'
services:
  api: 
    build: .
    container_name: api
    depends_on:
      - mysql
    ports:
      - "8080:80"
  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: qaltamore